# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'SMServer' do
  platform :ios, '16.0'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SMServer
  pod 'Telegraph'
  # I'm sorry that it's a local repo; this podspec is also available online for you to download:
  # https://raw.githubusercontent.com/iandwelker/Criollo/master/Criollo.podspec
  pod 'Criollo', :podspec => './Criollo.podspec'

  pod 'Starscream', '~> 4.0.0'

end

target 'SMServer_Mac' do
  platform :osx, '10.13'

  use_frameworks!

  pod 'Telegraph'
  pod 'Criollo', :podspec => './Criollo.podspec'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Bump deployment target to avoid libarclite missing in Xcode 14.3+
      current = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      unless current.nil?
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0' if current.to_f < 16.0
      end
      # Force arm64 only — bundled openssl.framework in Criollo has no arm64e slice
      config.build_settings['ARCHS'] = 'arm64'
      config.build_settings['VALID_ARCHS'] = 'arm64'
      config.build_settings['EXCLUDED_ARCHS'] = 'arm64e'
    end
  end
end
